# GitHub Actions Workflow for AI Manifest Health Check
# Place this file at: .github/workflows/ai-health-check.yml

name: AI Manifest Health Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run daily at 2am UTC
    - cron: '0 2 * * *'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run AI health check (simple)
        run: node invisible-users/code-examples/validation/verify-ai-simple.js

      - name: Run AI health check (production)
        run: node invisible-users/code-examples/validation/verify-ai-production.js

      - name: Notify on failure
        if: failure()
        run: echo "AI manifest validation failed! Check the logs above."
